// <auto-generated />
using System;
using Digi_Stihl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Digi_Stihl.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250720141357_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Digi_Stihl.Models.CapacityDeviation", b =>
                {
                    b.Property<int>("CapacityDeviationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CapacityDeviationId"));

                    b.Property<string>("Bemerkung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("NeueKapazitaet")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("CapacityDeviationId");

                    b.HasIndex("EmployeeId", "StartDate", "EndDate")
                        .IsUnique();

                    b.ToTable("CapacityDeviations");
                });

            modelBuilder.Entity("Digi_Stihl.Models.Department", b =>
                {
                    b.Property<string>("Kostenstelle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Abteilungsname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bereichsnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Kostenstelle");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Kostenstelle = "D001",
                            Abteilungsname = "Produktion",
                            Bereichsnummer = "01"
                        },
                        new
                        {
                            Kostenstelle = "D002",
                            Abteilungsname = "Vertrieb",
                            Bereichsnummer = "02"
                        },
                        new
                        {
                            Kostenstelle = "D003",
                            Abteilungsname = "Personal",
                            Bereichsnummer = "03"
                        },
                        new
                        {
                            Kostenstelle = "D004",
                            Abteilungsname = "IT",
                            Bereichsnummer = "04"
                        },
                        new
                        {
                            Kostenstelle = "D005",
                            Abteilungsname = "Verwaltung",
                            Bereichsnummer = "05"
                        },
                        new
                        {
                            Kostenstelle = "D007",
                            Abteilungsname = "Auszubildende",
                            Bereichsnummer = "07"
                        });
                });

            modelBuilder.Entity("Digi_Stihl.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("Arbeitsverhaeltnis")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Befristung")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BefristungMax")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bereich")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Eintritt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ExitReasonId")
                        .HasColumnType("int");

                    b.Property<decimal>("FTE")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime?>("Freistellung")
                        .HasColumnType("datetime2");

                    b.Property<string>("Funktion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kostenstelle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Kuendigung")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Mengenabhaengig")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Verlaengerung1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Verlaengerung2")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ExitReasonId");

                    b.HasIndex("Kostenstelle");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Digi_Stihl.Models.ExitReason", b =>
                {
                    b.Property<int>("ExitReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExitReasonId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.HasKey("ExitReasonId");

                    b.ToTable("ExitReasons");

                    b.HasData(
                        new
                        {
                            ExitReasonId = 1,
                            Description = "Eigenkündigung",
                            Reason = 0
                        },
                        new
                        {
                            ExitReasonId = 2,
                            Description = "Kündigung durch Arbeitgeber",
                            Reason = 1
                        },
                        new
                        {
                            ExitReasonId = 3,
                            Description = "Eintritt in Altersteilzeit",
                            Reason = 2
                        },
                        new
                        {
                            ExitReasonId = 4,
                            Description = "Ruhestand",
                            Reason = 3
                        },
                        new
                        {
                            ExitReasonId = 5,
                            Description = "Ende der Probezeit",
                            Reason = 4
                        });
                });

            modelBuilder.Entity("Digi_Stihl.Models.FluctuationReport", b =>
                {
                    b.Property<int>("FluctuationReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FluctuationReportId"));

                    b.Property<int>("AGKuendigungen")
                        .HasColumnType("int");

                    b.Property<int>("ANKuendigungen")
                        .HasColumnType("int");

                    b.Property<decimal>("Fluktuationsrate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Gesamtmitarbeiter")
                        .HasColumnType("int");

                    b.Property<int>("Jahr")
                        .HasColumnType("int");

                    b.Property<int>("Monat")
                        .HasColumnType("int");

                    b.Property<int>("SonstigeKuendigungen")
                        .HasColumnType("int");

                    b.HasKey("FluctuationReportId");

                    b.ToTable("FluctuationReports");
                });

            modelBuilder.Entity("Digi_Stihl.Models.CapacityDeviation", b =>
                {
                    b.HasOne("Digi_Stihl.Models.Employee", "Employee")
                        .WithMany("CapacityDeviations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Digi_Stihl.Models.Employee", b =>
                {
                    b.HasOne("Digi_Stihl.Models.ExitReason", "ExitReason")
                        .WithMany()
                        .HasForeignKey("ExitReasonId");

                    b.HasOne("Digi_Stihl.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("Kostenstelle");

                    b.Navigation("Department");

                    b.Navigation("ExitReason");
                });

            modelBuilder.Entity("Digi_Stihl.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Digi_Stihl.Models.Employee", b =>
                {
                    b.Navigation("CapacityDeviations");
                });
#pragma warning restore 612, 618
        }
    }
}
