// <auto-generated />
using System;
using Digi_Stihl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Digi_Stihl.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250331201428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Digi_Stihl.Models.CapacityDeviation", b =>
                {
                    b.Property<int>("CapacityDeviationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CapacityDeviationId"));

                    b.Property<string>("Bemerkung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Enddatum")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NeueKapazitaet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("datetime2");

                    b.HasKey("CapacityDeviationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CapacityDeviations");
                });

            modelBuilder.Entity("Digi_Stihl.Models.Department", b =>
                {
                    b.Property<string>("Kostenstelle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Abteilungsname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bereichsnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Kostenstelle");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Digi_Stihl.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Arbeitsverhaeltnis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Austrittsart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Befristung")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BefristungMax")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bereich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Eintritt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FTE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Freistellung")
                        .HasColumnType("datetime2");

                    b.Property<string>("Funktion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kostenstelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Kuendigung")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mengenabhaengig")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Verlaengerung1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Verlaengerung2")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Kostenstelle");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Digi_Stihl.Models.ExitReason", b =>
                {
                    b.Property<int>("ExitReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExitReasonId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExitReasonId");

                    b.ToTable("ExitReasons");
                });

            modelBuilder.Entity("Digi_Stihl.Models.FluctuationReport", b =>
                {
                    b.Property<int>("FluctuationReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FluctuationReportId"));

                    b.Property<int>("AGKuendigungen")
                        .HasColumnType("int");

                    b.Property<int>("ANKuendigungen")
                        .HasColumnType("int");

                    b.Property<decimal>("Fluktuationsrate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Gesamtmitarbeiter")
                        .HasColumnType("int");

                    b.Property<int>("Jahr")
                        .HasColumnType("int");

                    b.Property<int>("Monat")
                        .HasColumnType("int");

                    b.Property<int>("SonstigeKuendigungen")
                        .HasColumnType("int");

                    b.HasKey("FluctuationReportId");

                    b.ToTable("FluctuationReports");
                });

            modelBuilder.Entity("Digi_Stihl.Models.CapacityDeviation", b =>
                {
                    b.HasOne("Digi_Stihl.Models.Employee", "Employee")
                        .WithMany("CapacityDeviations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Digi_Stihl.Models.Employee", b =>
                {
                    b.HasOne("Digi_Stihl.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("Kostenstelle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Digi_Stihl.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Digi_Stihl.Models.Employee", b =>
                {
                    b.Navigation("CapacityDeviations");
                });
#pragma warning restore 612, 618
        }
    }
}
